name: Code checks

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: "Version patch"
        run: npm version 0.1.$GITHUB_RUN_ID

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: "Telegram Notification"
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: New 0.1.${{ github.run_id }} version publish
